export function generateFallbackQuestions() {
  return [
    {
      id: 'fb-1',
      domain: 'Behavioral',
      round: 'Introduction',
      roundName: 'Introduction',
      question: 'Tell me about yourself and the kind of impact you enjoy creating.',
      difficulty: 'Easy',
      type: 'behavioral',
    },
    {
      id: 'fb-2',
      domain: 'Behavioral',
      round: 'Introduction',
      roundName: 'Introduction',
      question: 'Why are you interested in this role at this company?',
      difficulty: 'Easy',
      type: 'behavioral',
    },
    {
      id: 'fb-3',
      domain: 'DSA',
      round: 'Technical',
      roundName: 'Technical',
      question: 'How would you find duplicates in an array efficiently?',
      difficulty: 'Medium',
      type: 'technical',
    },
    {
      id: 'fb-4',
      domain: 'System Design',
      round: 'Technical',
      roundName: 'Technical',
      question: 'Design a URL shortener and explain your data model.',
      difficulty: 'Medium',
      type: 'technical',
    },
    {
      id: 'fb-5',
      domain: 'Backend',
      round: 'Company-specific',
      roundName: 'Company-specific',
      question: 'How would you make an API endpoint idempotent?',
      difficulty: 'Medium',
      type: 'technical',
    },
    {
      id: 'fb-6',
      domain: 'Aptitude',
      round: 'Problem Solving',
      roundName: 'Problem Solving',
      question: 'If 5 people finish a task in 10 days, how long for 10 people?',
      difficulty: 'Easy',
      type: 'aptitude',
    },
    {
      id: 'fb-7',
      domain: 'Aptitude',
      round: 'Problem Solving',
      roundName: 'Problem Solving',
      question: 'What checks do you use to verify the correctness of your logic quickly?',
      difficulty: 'Easy',
      type: 'aptitude',
    },
    {
      id: 'fb-8',
      domain: 'Behavioral',
      round: 'Decision Making',
      roundName: 'Decision Making',
      question: 'Describe a tough deadline and how you prioritized your tasks.',
      difficulty: 'Medium',
      type: 'behavioral',
    },
    {
      id: 'fb-9',
      domain: 'Behavioral',
      round: 'Decision Making',
      roundName: 'Decision Making',
      question: 'Tell me about a conflict with a teammate and how you resolved it.',
      difficulty: 'Medium',
      type: 'behavioral',
    },
    {
      id: 'fb-10',
      domain: 'Communication',
      round: 'Wrap-up',
      roundName: 'Wrap-up',
      question: 'What are your top two learning goals for the next six months?',
      difficulty: 'Easy',
      type: 'behavioral',
    },
  ]
}

